# Generated by Django 4.1.3 on 2022-11-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="products",
            field=models.ManyToManyField(blank=True, to="product.product"),
        ),
    ]
